DELETE FROM PLAYLIST_MUSIQUE;
DELETE FROM PLAYLIST;
DELETE FROM MUSIQUE_GENRES;
DELETE FROM MUSIQUE;
DELETE FROM GENRE;

INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Jeff Healey', 220, null, 156, '01 I Would Do Anything For You.mp3', 'I Would Do Anything For You');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Sidney Bechet', 200, null, 170, '01 Muskrat Ramble (Ory).mp3', 'Muskrat Ramble');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Marc Laferrière', 240, 'Choré Balboa', 145, '01 Perdido street stomp.mp3', 'Perdido street stomp');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'The Hep Chaps', 165, null, 204, '01 Swingin'' on Nothing.mp3', 'Swingin'' on Nothing');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Paolo Conte', 165, null, 156, '01 Via Con Me.mp3', 'Via Con Me');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Biliie Holiday', 185, null, 195, '1-16 Spreadin'' Rhythm Around.mp3', 'Spreadin'' Rhythm Around');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Blue Skies', 138, null, 168, '02 Blue Skies.mp3', 'Blue Skies');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'The Bruce Fowler Big Band', 210, null, 188, '02 Chicago Shake.mp3', 'Chicago Shake');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Fats Waller', 230, null, 230, '02 Honeysuckle Rose - A Jam Session 1.mp3', 'Honeysuckle Rose - A Jam Session 1');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Fats Waller', 230, null, 230, '02 Honeysuckle Rose - A Jam Session.mp3', 'Honeysuckle Rose - A Jam Session');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Pee Wee Russel', 205, null, 271, '02 I Ain''t Gonna Give Nobody None of.m4a', 'I Ain''t Gonna Give Nobody None of my jelly rolls');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Big Bad Voodoo Daddy', 155, null, 263, '02 Merry Christmas Baby.mp3', 'Merry Christmas Baby');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Scott Bradley', 124, null, 182, '02 Thrift Shop.mp3', 'Thrift Shop');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'The Hep Chaps', 194, null, 199, '02 Tickle Toe.mp3', 'Tickle Toe');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Stuff Smith', 200, null, 205, '03 It Ain''t Right.mp3', 'It Ain''t Right');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Gentlemen & Gangsters', 194, null, 261, '03 Tin Roof Blues.mp3', 'Tin Roof Blues');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Oscar Aleman', 198, null, 247, '04 Besame Mucho.mp3', 'Besame Mucho');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Original soundtrack', 186, null, 259, '04 Boogie Man.mp3', 'Boogie Man');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Gordon Webster', 212, 'Super choré', 182, '04 Darktown Strutter''s Ball (Live).mp3', 'Darktown Strutter''s Ball (Live)');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Rhythm Junkies', 186, null, 194, '04 Dinah.mp3', 'Dinah');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'The Puppini Sisters', 216, null, 216, '04 Moi Je Joue.mp3', 'Moi Je Joue');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Jennie Lobel', 196, null, 186, '04 Tommy''s Low Bell.mp3', 'Tommy''s Low Bell');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Hot Sugar Band', 192, null, 175, '04 Yacht club swing.mp3', 'Yacht club swing');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Preservation Hall Jazz Band', 188, null, 175, '05 Dr. Jazz.mp3', 'Dr. Jazz');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Rhythm Junkies', 188, null, 175, '05 That''s a plenty.mp3', 'That''s a plenty');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Gordon Webster', 128, null, 305, '06 Blues My Naughty Sweetie Gives To.mp3', 'Blues My Naughty Sweetie Gives To Me');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Gentlemen & Gangsters', 144, null, 156, '06 Bugsy.mp3', 'Bugsy');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Gentlemen & Gangsters', 116, null, 183, '06 Darkness on the Delta.mp3', 'Darkness on the Delta');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Artie Shaw', 208, null, 143, '06 The Carioca.mp3', 'The Carioca');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'The Red Clay Ramblers', 192, null, 191, '07 It Ain''t Right.mp3', 'It Ain''t Right');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Jeff Healey', 124, null, 164, '08 A Cup Of Coffee, A Sandwich, And.mp3', 'A Cup Of Coffee, A Sandwich, And');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'The Dream Team', 146, null, 184, '08 Happy Feet.mp3', 'Happy Feet');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Papa''s Finest Boogie Band', 146, null, 184, '08 Sense of Life.mp3', 'Sense of Life');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Brother Yusef', 220, null, 231, '08 Shoes of another man.mp3', 'Shoes of another man');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Pee Wee Russel', 224, null, 221, '08 That Da-Da Strain.m4a', 'That Da-Da Strain');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Swing Christmas', 164, null, 192, '08 The Skater''s Waltz (In Swingtime).mp3', 'The Skater''s Waltz (In Swingtime)');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Michel Pastre Big Band', 140, null, 192, '08 Tickle Toe.mp3', 'Tickle Toe');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Mike Daniels Delta Jazzmen', 158, null, 201, '09 Big Fat Ham.mp3', 'Big Fat Ham');
INSERT INTO MUSIQUE(id, artiste, bpm, commentaire, duree, path, titre) VALUES (MUSIQUE_SEQ.nextval, 'Gentlemen & Gangsters', 160, null, 202, '09 I''ll See You In My Dreams.mp3', 'I''ll See You In My Dreams');

INSERT INTO GENRE(id, label) VALUES (GENRE_SEQ.nextval, 'Lindy');
INSERT INTO GENRE(id, label) VALUES (GENRE_SEQ.nextval, 'Balboa');
INSERT INTO GENRE(id, label) VALUES (GENRE_SEQ.nextval, '4 temps');
INSERT INTO GENRE(id, label) VALUES (GENRE_SEQ.nextval, '6 temps');
INSERT INTO GENRE(id, label) VALUES (GENRE_SEQ.nextval, 'Boogie');
INSERT INTO GENRE(id, label) VALUES (GENRE_SEQ.nextval, 'Blues');

INSERT INTO MUSIQUE_GENRES(id_musique, id_genre) SELECT id, (SELECT id FROM GENRE WHERE label = 'Lindy') FROM MUSIQUE;
