DROP TABLE MUSIQUE IF EXISTS;
CREATE TABLE MUSIQUE(
  itunes_id INT(11) NOT NULL PRIMARY KEY,
  titre VARCHAR(100) NOT NULL,
  artiste VARCHAR(100) NULL,
  genre VARCHAR(100) NULL,
  duree INT(11) NULL,
  timer_debut INT(11) NULL,
  timer_fin INT(11) NULL,
  bpm INT(11) NULL,
  classement INT(3) NULL,
  commentaire VARCHAR(255) NULL,
  path VARCHAR(255) NULL
);

DROP TABLE PLAYLIST IF EXISTS;
CREATE TABLE PLAYLIST(
  itunes_id INT(11) NOT NULL PRIMARY KEY,
  nom VARCHAR(100) NOT NULL,
  is_folder INT(1) NULL,
  persistent_id VARCHAR(30) NULL,
  parent_persistent_id VARCHAR(30) NULL,
  id_playlist_parent INT(11) NULL,
);

DROP TABLE PLAYLIST_MUSIQUE IF EXISTS;
CREATE TABLE PLAYLIST_MUSIQUE (
  id_playlist INT(11) NOT NULL,
  id_musique INT(11) NOT NULL
);

ALTER TABLE PLAYLIST_MUSIQUE ADD CONSTRAINT PK_PLAYLIST_MUSIQUE PRIMARY KEY (id_playlist, id_musique);

